import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from '@/components/ui/dialog'
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
} from '@/components/ui/form'
import {
  deleteRecurrenceSchema,
  DELETE_RECURRENCE_STRATEGIES,
  type DeleteRecurrenceFormValues,
} from '@/features/recurrences/schemas/delete-recurrence.schema'
import { useDeleteRecurrence } from '@/features/recurrences/hooks/use-delete-recurrence'
import { NativeSelect } from './recurrence-form-fields'
import type { Recurrence } from '@/features/recurrences/types'

const STRATEGY_LABELS: Record<string, string> = {
  FUTURE_ONLY: 'Future Only — keep past transactions, delete only future ones',
  ALL: 'All — delete all transactions generated by this rule',
}

interface DeleteRecurrenceDialogProps {
  recurrence: Recurrence | null
  open: boolean
  onClose: () => void
}

export function DeleteRecurrenceDialog({ recurrence, open, onClose }: DeleteRecurrenceDialogProps) {
  const { mutate: deleteRecurrence, isPending } = useDeleteRecurrence()

  const form = useForm<DeleteRecurrenceFormValues>({
    resolver: zodResolver(deleteRecurrenceSchema),
    defaultValues: { strategy: 'FUTURE_ONLY' },
  })

  function onSubmit(data: DeleteRecurrenceFormValues) {
    if (!recurrence) return
    deleteRecurrence(
      { id: recurrence.id, strategy: data.strategy },
      {
        onSuccess: () => {
          form.reset()
          onClose()
        },
      },
    )
  }

  function handleOpenChange(isOpen: boolean) {
    if (!isOpen) {
      form.reset()
      onClose()
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Delete Recurrence Rule</DialogTitle>
          <DialogDescription>
            You are about to delete the rule{' '}
            <span className="font-semibold">{recurrence?.description}</span>. Choose how existing
            transactions should be handled.
          </DialogDescription>
        </DialogHeader>

        <div
          className="rounded-md border border-muted bg-muted/40 px-4 py-3 space-y-2 text-sm"
          role="note"
        >
          <p>
            <span className="font-medium">Future Only:</span> Transactions already recorded are
            kept. Only future transactions that have not yet been generated will be removed.
          </p>
          <p>
            <span className="font-medium">All:</span> All transactions generated by this rule — past
            and future — will be permanently deleted. This action cannot be undone.
          </p>
        </div>

        <Form {...form}>
          <form
            id="delete-recurrence-form"
            onSubmit={form.handleSubmit(onSubmit)}
            noValidate
            className="space-y-4"
          >
            <FormField
              control={form.control}
              name="strategy"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Deletion Strategy</FormLabel>
                  <FormControl>
                    <NativeSelect aria-label="Deletion Strategy" {...field}>
                      {DELETE_RECURRENCE_STRATEGIES.map((strategy) => (
                        <option key={strategy} value={strategy}>
                          {STRATEGY_LABELS[strategy]}
                        </option>
                      ))}
                    </NativeSelect>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </form>
        </Form>

        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => handleOpenChange(false)}>
            Cancel
          </Button>
          <Button
            type="submit"
            form="delete-recurrence-form"
            variant="destructive"
            disabled={isPending}
            aria-busy={isPending}
          >
            {isPending ? (
              <>
                <span
                  className="w-4 h-4 border-2 border-destructive-foreground border-t-transparent rounded-full animate-spin"
                  aria-hidden="true"
                />
                Deleting…
              </>
            ) : (
              'Delete Rule'
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
