import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/ui/modal'
import { Field } from '@/components/ui/field'
import { Select } from '@/components/ui/select'
import {
  deleteRecurrenceSchema,
  DELETE_RECURRENCE_STRATEGIES,
  type DeleteRecurrenceFormValues,
} from '@/features/recurrences/schemas/delete-recurrence.schema'
import { useDeleteRecurrence } from '@/features/recurrences/hooks/use-delete-recurrence'
import type { Recurrence } from '@/features/recurrences/types'

const STRATEGY_LABELS: Record<string, string> = {
  FUTURE_ONLY: 'Future Only — keep past transactions, delete only future ones',
  ALL: 'All — delete all transactions generated by this rule',
}

interface DeleteRecurrenceDialogProps {
  recurrence: Recurrence | null
  open: boolean
  onClose: () => void
}

export function DeleteRecurrenceDialog({ recurrence, open, onClose }: DeleteRecurrenceDialogProps) {
  const { mutate: deleteRecurrence, isPending } = useDeleteRecurrence()

  const form = useForm<DeleteRecurrenceFormValues>({
    resolver: zodResolver(deleteRecurrenceSchema),
    defaultValues: { strategy: 'FUTURE_ONLY' },
  })

  function onSubmit(data: DeleteRecurrenceFormValues) {
    if (!recurrence) return
    deleteRecurrence(
      { id: recurrence.id, strategy: data.strategy },
      {
        onSuccess: () => {
          form.reset()
          onClose()
        },
      },
    )
  }

  function handleClose() {
    form.reset()
    onClose()
  }

  if (!open) return null

  return (
    <Modal
      title="Delete Recurrence Rule"
      onClose={handleClose}
      footer={
        <>
          <Button type="button" variant="ghost" onClick={handleClose}>
            Cancel
          </Button>
          <div className="spacer" />
          <Button
            type="submit"
            form="delete-recurrence-form"
            variant="danger"
            disabled={isPending}
            aria-busy={isPending}
          >
            {isPending ? (
              <>
                <span
                  className="animate-spin"
                  style={{
                    width: 14,
                    height: 14,
                    border: '2px solid currentColor',
                    borderTopColor: 'transparent',
                    borderRadius: '50%',
                    display: 'inline-block',
                  }}
                  aria-hidden="true"
                />
                Deleting…
              </>
            ) : (
              'Delete Rule'
            )}
          </Button>
        </>
      }
    >
      <p>
        You are about to delete the rule <strong>{recurrence?.description}</strong>. Choose how
        existing transactions should be handled.
      </p>

      <div
        className="rounded-md border border-muted bg-muted/40 px-4 py-3 space-y-2 text-sm"
        role="note"
        style={{ marginTop: 12 }}
      >
        <p>
          <span className="font-medium">Future Only:</span> Transactions already recorded are kept.
          Only future transactions that have not yet been generated will be removed.
        </p>
        <p>
          <span className="font-medium">All:</span> All transactions generated by this rule — past
          and future — will be permanently deleted. This action cannot be undone.
        </p>
      </div>

      <form
        id="delete-recurrence-form"
        onSubmit={form.handleSubmit(onSubmit)}
        noValidate
        className="col gap-4"
        style={{ marginTop: 12 }}
      >
        <Field label="Deletion Strategy" error={form.formState.errors.strategy?.message}>
          <Select aria-label="Deletion Strategy" {...form.register('strategy')}>
            {DELETE_RECURRENCE_STRATEGIES.map((strategy) => (
              <option key={strategy} value={strategy}>
                {STRATEGY_LABELS[strategy]}
              </option>
            ))}
          </Select>
        </Field>
      </form>
    </Modal>
  )
}
