// CSS var references for Tailwind — enables bg-accent, text-income, etc.
export const colors = {
  accent: 'var(--accent)',
  'accent-hover': 'var(--accent-hover)',
  'accent-press': 'var(--accent-press)',
  'accent-soft': 'var(--accent-soft)',
  'accent-fg': 'var(--accent-fg)',
  bg: 'var(--bg)',
  'surface-1': 'var(--surface-1)',
  'surface-2': 'var(--surface-2)',
  'surface-3': 'var(--surface-3)',
  'surface-hover': 'var(--surface-hover)',
  border: 'var(--border)',
  'border-strong': 'var(--border-strong)',
  text: 'var(--text)',
  'text-muted': 'var(--text-muted)',
  'text-dim': 'var(--text-dim)',
  'text-faint': 'var(--text-faint)',
  paid: 'var(--paid)',
  'paid-soft': 'var(--paid-soft)',
  pending: 'var(--pending)',
  'pending-soft': 'var(--pending-soft)',
  cancelled: 'var(--cancelled)',
  'cancelled-soft': 'var(--cancelled-soft)',
  income: 'var(--income)',
  'income-soft': 'var(--income-soft)',
  expense: 'var(--expense)',
  'expense-soft': 'var(--expense-soft)',
  info: 'var(--info)',
  'info-soft': 'var(--info-soft)',
} as const

// Raw hex palette (dark theme defaults) for TypeScript consumers
export const palette = {
  accent: '#ff6b35',
  accentHover: '#ff8559',
  accentPress: '#e85a26',
  accentFg: '#0a0a0b',
  bg: '#0a0a0b',
  surface1: '#101012',
  surface2: '#16161a',
  surface3: '#1d1d22',
  border: '#232328',
  borderStrong: '#2e2e36',
  text: '#f4f4f5',
  textMuted: '#a1a1aa',
  textDim: '#71717a',
  textFaint: '#52525b',
  paid: '#34d399',
  pending: '#fbbf24',
  cancelled: '#71717a',
  income: '#34d399',
  expense: '#fb7185',
  info: '#60a5fa',
} as const
